const express = require('express');
const cors = require('cors');
const jsonServer = require('json-server');

const app = express();
app.use(cors());
app.use(express.json());

// Create a JSON Server instance
const server = jsonServer.create();

// Get the router generated by JSON Server
const router = jsonServer.router('./db.json');

// Specify custom routes if needed
// For example:
// server.get('/custom-route', (req, res) => {
//   // Handle custom route logic here
// });

// Apply the JSON Server middleware
app.use('/api', server);
app.use('/api', router);

// Start the server
app.listen(5000, () => {
  console.log('Server is running on port 5000');
});